import Head from "next/head";
import Navbar from "./components/Navbar";
import styles from "../styles/Home.module.scss";
import AddNewproducts from "./AddNewProduct";
import Products from "./Products";

export default function Home(handleEdit) {
  return (
    <div className={styles.content}>
      <Head>
        <title>Fake Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo1.ico" />
      </Head>

      {/* <Navbar/> 

      <h1>All Product</h1>
      {/* <a href="/AddNewProduct">
        <button class="bn54">
          <span class="bn54span">Add New Product</span>
        </button>
      </a>*/}

      <Products />
    </div>
  );
}
