import Head from "next/head";
import Navbar from "./components/Navbar";
import styles from "../styles/Home.module.scss";
import AddNewproducts from "./AddNewProduct";

export default function Home() {
  return (
    <div className={styles.content}>
      <Head>
        <title>Fake Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Navbar/> 

      <h1>All Product</h1>
      {/* <a href="/AddNewProduct">
        <button class="bn54">
          <span class="bn54span">Add New Product</span>
        </button>
      </a>*/}
      <AddNewproducts />
    </div>
  );
}
